CREATE TYPE "RefundStatus" AS ENUM ('REQUESTED', 'APPROVED', 'READY_FOR_PROVIDER_REFUND', 'COMPLETED', 'FAILED', 'REJECTED');
CREATE TYPE "ReturnStatus" AS ENUM ('REQUESTED', 'APPROVED', 'REJECTED', 'RECEIVED', 'COMPLETED');
ALTER TYPE "LedgerTransactionType" ADD VALUE IF NOT EXISTS 'SALE_REVERSAL_PENDING';
ALTER TYPE "LedgerTransactionType" ADD VALUE IF NOT EXISTS 'SALE_REVERSAL_AVAILABLE';
ALTER TYPE "LedgerTransactionType" ADD VALUE IF NOT EXISTS 'PLATFORM_COMMISSION_REVERSAL';
ALTER TABLE "FinancialLedger" ADD COLUMN "refundId" TEXT;
DROP INDEX "FinancialLedger_subOrderId_paymentAttemptId_type_key";
CREATE UNIQUE INDEX "FinancialLedger_subOrderId_paymentAttemptId_type_key" ON "FinancialLedger"("subOrderId", "paymentAttemptId", "type") WHERE "refundId" IS NULL;
CREATE UNIQUE INDEX "FinancialLedger_refundId_type_key" ON "FinancialLedger"("refundId", "type");
CREATE INDEX "FinancialLedger_refundId_idx" ON "FinancialLedger"("refundId");
CREATE TABLE "ReturnRequest" ("id" TEXT NOT NULL, "subOrderId" TEXT NOT NULL, "requestedByUserId" TEXT NOT NULL, "status" "ReturnStatus" NOT NULL DEFAULT 'REQUESTED', "reason" TEXT NOT NULL, "receivedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ReturnRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ReturnItem" ("id" TEXT NOT NULL, "returnRequestId" TEXT NOT NULL, "orderItemId" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "restockedAt" TIMESTAMP(3), CONSTRAINT "ReturnItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Refund" ("id" TEXT NOT NULL, "orderId" TEXT NOT NULL, "subOrderId" TEXT NOT NULL, "paymentAttemptId" TEXT, "returnRequestId" TEXT, "requestedByUserId" TEXT NOT NULL, "approvedByUserId" TEXT, "amount" DECIMAL(18,2) NOT NULL, "currency" VARCHAR(3) NOT NULL, "reason" TEXT NOT NULL, "status" "RefundStatus" NOT NULL DEFAULT 'REQUESTED', "approvedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Refund_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ReturnItem_returnRequestId_orderItemId_key" ON "ReturnItem"("returnRequestId", "orderItemId");
CREATE UNIQUE INDEX "Refund_returnRequestId_key" ON "Refund"("returnRequestId");
CREATE INDEX "ReturnRequest_subOrderId_status_idx" ON "ReturnRequest"("subOrderId", "status");
CREATE INDEX "ReturnRequest_requestedByUserId_idx" ON "ReturnRequest"("requestedByUserId");
CREATE INDEX "ReturnItem_orderItemId_idx" ON "ReturnItem"("orderItemId");
CREATE INDEX "Refund_subOrderId_status_idx" ON "Refund"("subOrderId", "status");
CREATE INDEX "Refund_orderId_idx" ON "Refund"("orderId");
CREATE INDEX "Refund_paymentAttemptId_idx" ON "Refund"("paymentAttemptId");
ALTER TABLE "FinancialLedger" ADD CONSTRAINT "FinancialLedger_refundId_fkey" FOREIGN KEY ("refundId") REFERENCES "Refund"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReturnRequest" ADD CONSTRAINT "ReturnRequest_subOrderId_fkey" FOREIGN KEY ("subOrderId") REFERENCES "SubOrder"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReturnRequest" ADD CONSTRAINT "ReturnRequest_requestedByUserId_fkey" FOREIGN KEY ("requestedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReturnItem" ADD CONSTRAINT "ReturnItem_returnRequestId_fkey" FOREIGN KEY ("returnRequestId") REFERENCES "ReturnRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ReturnItem" ADD CONSTRAINT "ReturnItem_orderItemId_fkey" FOREIGN KEY ("orderItemId") REFERENCES "OrderItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_subOrderId_fkey" FOREIGN KEY ("subOrderId") REFERENCES "SubOrder"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_paymentAttemptId_fkey" FOREIGN KEY ("paymentAttemptId") REFERENCES "PaymentAttempt"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_returnRequestId_fkey" FOREIGN KEY ("returnRequestId") REFERENCES "ReturnRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_requestedByUserId_fkey" FOREIGN KEY ("requestedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_approvedByUserId_fkey" FOREIGN KEY ("approvedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
