import { MarketplaceReportActivityType, MarketplaceReportReason, MarketplaceReportResolution, MarketplaceReportSeverity, MarketplaceReportStatus, MarketplaceReportTargetType, PlatformRole, UserStatus } from "@prisma/client";
import { requireActiveUserId } from "@/lib/auth/session";
import { requireAdminContext } from "@/lib/auth/admin-context";
import { prisma } from "@/lib/prisma/client";

export class MarketplaceReportError extends Error { constructor(message: string, public code = "INVALID") { super(message); } }

const reasons: Record<MarketplaceReportTargetType, MarketplaceReportReason[]> = {
  PRODUCT: ["COUNTERFEIT", "MISLEADING_INFORMATION", "PROHIBITED_ITEM", "INAPPROPRIATE_CONTENT", "WRONG_CATEGORY", "PRICE_MANIPULATION", "INTELLECTUAL_PROPERTY", "SCAM_OR_FRAUD", "SPAM", "OTHER"],
  SHOP: ["MISLEADING_INFORMATION", "INAPPROPRIATE_CONTENT", "SCAM_OR_FRAUD", "IMPERSONATION", "ABUSIVE_BEHAVIOR", "SPAM", "OTHER"],
};
const openStatuses: MarketplaceReportStatus[] = ["SUBMITTED", "UNDER_REVIEW", "AWAITING_INFORMATION", "ACTION_REQUIRED"];
const transitions: Record<MarketplaceReportStatus, MarketplaceReportStatus[]> = {
  SUBMITTED: ["UNDER_REVIEW"], UNDER_REVIEW: ["AWAITING_INFORMATION", "ACTION_REQUIRED", "RESOLVED", "DISMISSED"], AWAITING_INFORMATION: ["UNDER_REVIEW"], ACTION_REQUIRED: ["UNDER_REVIEW", "RESOLVED"], RESOLVED: [], DISMISSED: [],
};

function clean(value: unknown, max: number) { return typeof value === "string" ? value.trim().replace(/\s+/g, " ").slice(0, max) : ""; }
function customerStatus(status: MarketplaceReportStatus) { return status === "AWAITING_INFORMATION" ? "More information required" : status === "RESOLVED" ? "Resolved" : status === "DISMISSED" ? "Closed" : status === "SUBMITTED" ? "Submitted" : "Under review"; }
function noteForStatus(publicId: string, status: MarketplaceReportStatus) { if (status === "UNDER_REVIEW") return `Your report ${publicId} is now under review.`; if (status === "AWAITING_INFORMATION") return `We need additional information to continue reviewing report ${publicId}.`; if (status === "RESOLVED") return `We've completed our review of report ${publicId}. Appropriate action has been taken.`; return `We've completed our review of report ${publicId} and the case has been closed.`; }

export class MarketplaceReportService {
  static async createForCurrentUser(input: { targetType: MarketplaceReportTargetType; targetId: string; reason: MarketplaceReportReason; description?: string }) {
    const reporterId = await requireActiveUserId();
    const description = clean(input.description, 2000);
    if (!Object.hasOwn(reasons, input.targetType) || !reasons[input.targetType].includes(input.reason)) throw new MarketplaceReportError("That reason is not available for this report target.");
    if (input.reason === "OTHER" && description.length < 10) throw new MarketplaceReportError("Please provide a short explanation for Other.");
    if (description.length && description.length < 3) throw new MarketplaceReportError("Please provide a more detailed description.");
    const product = input.targetType === "PRODUCT" ? await prisma.product.findFirst({ where: { id: input.targetId, deletedAt: null }, select: { id: true, name: true, slug: true, vendorId: true, vendor: { select: { storeName: true } }, images: { where: { isFeatured: true }, take: 1, select: { url: true } } } }) : null;
    const shop = input.targetType === "SHOP" ? await prisma.vendorProfile.findFirst({ where: { id: input.targetId, deletedAt: null }, select: { id: true, storeName: true, slug: true, logoUrl: true } }) : null;
    if (!product && !shop) throw new MarketplaceReportError("The item you are trying to report is no longer available.", "NOT_FOUND");
    const targetWhere = product ? { productId: product.id } : { vendorId: shop!.id };
    const existing = await prisma.marketplaceReport.findFirst({ where: { reporterId, targetType: input.targetType, reason: input.reason, status: { in: openStatuses }, ...targetWhere }, select: { publicId: true } });
    if (existing) throw new MarketplaceReportError(`You already have an active report for this reason (${existing.publicId}).`, "DUPLICATE");
    const now = new Date(); const publicId = `RPT-${now.getUTCFullYear()}-${crypto.randomUUID().replace(/-/g, "").slice(0, 8).toUpperCase()}`;
    const snapshot = product ? { targetTitleSnapshot: product.name, targetSlugSnapshot: product.slug, targetImageSnapshot: product.images[0]?.url, vendorIdSnapshot: product.vendorId, vendorNameSnapshot: product.vendor.storeName, productId: product.id, vendorId: product.vendorId } : { targetTitleSnapshot: shop!.storeName, targetSlugSnapshot: shop!.slug, targetImageSnapshot: shop!.logoUrl, vendorIdSnapshot: shop!.id, vendorNameSnapshot: shop!.storeName, vendorId: shop!.id };
    return prisma.$transaction(async (tx) => {
      const report = await tx.marketplaceReport.create({ data: { publicId, targetType: input.targetType, reporterId, reason: input.reason, description: description || null, ...snapshot } });
      await tx.marketplaceReportActivity.create({ data: { reportId: report.id, actorId: reporterId, type: MarketplaceReportActivityType.REPORT_CREATED } });
      await tx.notification.create({ data: { userId: reporterId, type: "INFO", title: "Report received", message: `Your report about “${report.targetTitleSnapshot}” has been received and is awaiting review.`, actionPath: `/account/reports/${report.id}` } });
      return report;
    });
  }

  static async listForCurrentUser() { const reporterId = await requireActiveUserId(); const items = await prisma.marketplaceReport.findMany({ where: { reporterId }, orderBy: { createdAt: "desc" } }); return items.map(({ severity: _severity, assignedAdminId: _assigned, ...report }) => ({ ...report, customerStatus: customerStatus(report.status) })); }
  static async getForCurrentUser(id: string) { const reporterId = await requireActiveUserId(); const report = await prisma.marketplaceReport.findFirst({ where: { id, reporterId }, include: { activities: { where: { type: { in: ["REPORT_CREATED", "STATUS_CHANGED", "REPORT_RESOLVED", "REPORT_DISMISSED"] } }, orderBy: { createdAt: "asc" } } } }); if (!report) throw new MarketplaceReportError("Report not found.", "NOT_FOUND"); const { severity: _severity, assignedAdminId: _assigned, assignedById: _by, activities, ...safe } = report; return { ...safe, customerStatus: customerStatus(report.status), activities: activities.map(({ metadata: _metadata, actorId: _actor, ...activity }) => activity) }; }
  static async listForAdmin(input: { status?: MarketplaceReportStatus; severity?: MarketplaceReportSeverity; targetType?: MarketplaceReportTargetType; reason?: MarketplaceReportReason; assignedAdminId?: string; unassigned?: boolean; quickView?: string; page?: number; limit?: number } = {}) { const admin = await requireAdminContext("platform:customer_support"); const enumValue = (value?: string) => value?.toUpperCase().replaceAll(" ", "_"); const page = Math.max(1, input.page ?? 1), limit = Math.min(100, Math.max(1, input.limit ?? 25)); const where: any = { ...(input.status ? { status: enumValue(input.status) } : {}), ...(input.severity ? { severity: enumValue(input.severity) } : {}), ...(input.targetType ? { targetType: enumValue(input.targetType) } : {}), ...(input.reason ? { reason: enumValue(input.reason) } : {}), ...(input.assignedAdminId ? { assignedAdminId: input.assignedAdminId } : {}), ...(input.unassigned ? { assignedAdminId: null } : {}) }; if (input.quickView === "mine") where.assignedAdminId = admin.userId; if (input.quickView === "unassigned") where.assignedAdminId = null; if (input.quickView === "critical") where.severity = "CRITICAL"; if (input.quickView === "new") where.status = "SUBMITTED"; if (input.quickView === "resolved") where.status = "RESOLVED"; const start = new Date(); start.setHours(0, 0, 0, 0); const [items, total, open, unassigned, critical, resolvedToday] = await prisma.$transaction([prisma.marketplaceReport.findMany({ where, include: { reporter: { select: { name: true, email: true } }, assignedAdmin: { select: { name: true } } }, orderBy: input.quickView === "resolved" ? { resolvedAt: "desc" } : { createdAt: "desc" }, skip: (page - 1) * limit, take: limit }), prisma.marketplaceReport.count({ where }), prisma.marketplaceReport.count({ where: { status: { in: openStatuses } } }), prisma.marketplaceReport.count({ where: { assignedAdminId: null, status: { in: openStatuses } } }), prisma.marketplaceReport.count({ where: { severity: "CRITICAL", status: { in: openStatuses } } }), prisma.marketplaceReport.count({ where: { status: "RESOLVED", resolvedAt: { gte: start } } })]); return { items, total, page, limit, metrics: { open, unassigned, critical, resolvedToday } }; }
  static async eligibleAdmins() { await requireAdminContext("platform:customer_support"); return prisma.user.findMany({ where: { status: UserStatus.ACTIVE, platformRole: { in: [PlatformRole.SUPER_ADMIN, PlatformRole.ADMIN, PlatformRole.SUPPORT] } }, select: { id: true, name: true, email: true, platformRole: true }, orderBy: { name: "asc" } }); }
  static async getForAdmin(id: string) { await requireAdminContext("platform:customer_support"); return prisma.marketplaceReport.findUnique({ where: { id }, include: { reporter: { select: { name: true, email: true } }, assignedAdmin: { select: { name: true, email: true } }, activities: { include: { actor: { select: { name: true } } }, orderBy: { createdAt: "asc" } }, notes: { include: { admin: { select: { name: true } } }, orderBy: { createdAt: "asc" } } } }); }
  static async assign(id: string, assignedAdminId: string) { const actor = await requireAdminContext("platform:customer_support"); const assignee = await prisma.user.findFirst({ where: { id: assignedAdminId, status: UserStatus.ACTIVE, platformRole: { in: [PlatformRole.SUPER_ADMIN, PlatformRole.ADMIN, PlatformRole.SUPPORT] } }, select: { id: true } }); if (!assignee) throw new MarketplaceReportError("Choose an eligible active administrator."); const report = await prisma.marketplaceReport.findUnique({ where: { id } }); if (!report) throw new MarketplaceReportError("Report not found.", "NOT_FOUND"); return prisma.$transaction(async tx => { const updated = await tx.marketplaceReport.update({ where: { id }, data: { assignedAdminId, assignedAt: new Date(), assignedById: actor.userId } }); await tx.marketplaceReportActivity.create({ data: { reportId: id, actorId: actor.userId, type: report.assignedAdminId ? "REASSIGNED" : "ASSIGNED", fromValue: report.assignedAdminId, toValue: assignedAdminId } }); await tx.notification.create({ data: { userId: assignedAdminId, type: "WARNING", title: "Report assigned", message: `${report.publicId} has been assigned to you.`, actionPath: `/admin/reports/${id}` } }); await tx.auditLog.create({ data: { userId: actor.userId, action: "MARKETPLACE_REPORT_ASSIGNED", entity: "MarketplaceReport", entityId: id, newValues: { assignedAdminId } } }); return updated; }); }
  static async setSeverity(id: string, severity: MarketplaceReportSeverity) { const actor = await requireAdminContext("platform:customer_support"); const report = await prisma.marketplaceReport.findUnique({ where: { id } }); if (!report) throw new MarketplaceReportError("Report not found.", "NOT_FOUND"); return prisma.$transaction(async tx => { const updated = await tx.marketplaceReport.update({ where: { id }, data: { severity } }); await tx.marketplaceReportActivity.create({ data: { reportId: id, actorId: actor.userId, type: "SEVERITY_CHANGED", fromValue: report.severity, toValue: severity } }); await tx.auditLog.create({ data: { userId: actor.userId, action: "MARKETPLACE_REPORT_SEVERITY_CHANGED", entity: "MarketplaceReport", entityId: id, oldValues: { severity: report.severity }, newValues: { severity } } }); return updated; }); }
  static async transition(id: string, status: MarketplaceReportStatus, resolution?: MarketplaceReportResolution, resolutionNote?: string) { const actor = await requireAdminContext("platform:customer_support"); const report = await prisma.marketplaceReport.findUnique({ where: { id } }); if (!report) throw new MarketplaceReportError("Report not found.", "NOT_FOUND"); if (!transitions[report.status].includes(status)) throw new MarketplaceReportError("That status transition is not allowed."); const note = clean(resolutionNote, 2000); if (status === "RESOLVED" && (!resolution || (resolution === "OTHER" && note.length < 10))) throw new MarketplaceReportError("A meaningful resolution and note are required."); if (status === "DISMISSED" && note.length < 3) throw new MarketplaceReportError("A dismissal note is required."); return prisma.$transaction(async tx => { const resolved = status === "RESOLVED" || status === "DISMISSED"; const updated = await tx.marketplaceReport.update({ where: { id }, data: { status, ...(resolved ? { resolution: resolution ?? "NO_VIOLATION", resolutionNote: note, resolvedById: actor.userId, resolvedAt: new Date() } : {}) } }); await tx.marketplaceReportActivity.create({ data: { reportId: id, actorId: actor.userId, type: status === "RESOLVED" ? "REPORT_RESOLVED" : status === "DISMISSED" ? "REPORT_DISMISSED" : "STATUS_CHANGED", fromValue: report.status, toValue: status } }); if (["UNDER_REVIEW", "AWAITING_INFORMATION", "RESOLVED", "DISMISSED"].includes(status)) await tx.notification.create({ data: { userId: report.reporterId, type: status === "RESOLVED" ? "SUCCESS" : status === "DISMISSED" ? "INFO" : "WARNING", title: "Report update", message: noteForStatus(report.publicId, status), actionPath: `/account/reports/${id}` } }); await tx.auditLog.create({ data: { userId: actor.userId, action: `MARKETPLACE_REPORT_${status}`, entity: "MarketplaceReport", entityId: id, newValues: { status, resolution } } }); return updated; }); }
  static async addNote(id: string, body: string) { const actor = await requireAdminContext("platform:customer_support"); const text = clean(body, 4000); if (text.length < 2) throw new MarketplaceReportError("Enter an internal note."); return prisma.$transaction(async tx => { const report = await tx.marketplaceReport.findUnique({ where: { id }, select: { id: true } }); if (!report) throw new MarketplaceReportError("Report not found.", "NOT_FOUND"); const note = await tx.marketplaceReportNote.create({ data: { reportId: id, adminId: actor.userId, body: text } }); await tx.marketplaceReportActivity.create({ data: { reportId: id, actorId: actor.userId, type: "NOTE_ADDED" } }); return note; }); }
}
