import { ReconciliationDomain, ReconciliationFindingStatus, ReconciliationSeverity } from "@prisma/client";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "@/lib/prisma/client";
import { requireAdminContext } from "@/lib/auth/admin-context";
import { MarketplaceEconomicsService } from "@/services/marketplace-economics";
import { ReturnsRefundsService } from "@/services/returns-refunds";
import { PayoutReadinessService } from "@/services/payout-readiness";

const ZERO = new Decimal(0), BATCH_SIZE = 100;
export type ReconciliationScope = "PAYMENTS" | "EARNINGS" | "PAYOUTS" | "REFUNDS" | "REVERSALS" | "RISK" | "ALL";
export type Fact = { type:string; domain:ReconciliationDomain; severity:ReconciliationSeverity; entityType:string; entityId:string; vendorId?:string; orderId?:string; subOrderId?:string; paymentAttemptId?:string; vendorPayoutId?:string; refundId?:string; metadata?:object };
type Ledger = { type:string; amount:Decimal; currency?:string|null; paymentAttemptId?:string|null; subOrderId?:string|null; vendorId?:string; walletBucket?:string|null };
const total = (items:Array<{amount:Decimal}>) => items.reduce((n,x) => n.plus(x.amount), ZERO);
const make = (type:string,domain:ReconciliationDomain,severity:ReconciliationSeverity,entityType:string,entityId:string,ids:Partial<Fact>={},metadata?:object):Fact => ({type,domain,severity,entityType,entityId,...ids,metadata});

export const detectPaymentOrderMismatch=(a:{id:string;status:string;orderId:string;order:{paymentStatus:string}}):Fact[]=>a.status==="COMPLETED"&&a.order.paymentStatus!=="COMPLETED"?[make("PAYMENT_COMPLETED_ORDER_MISMATCH","PAYMENT","HIGH","PaymentAttempt",a.id,{orderId:a.orderId,paymentAttemptId:a.id})]:[];
export const detectEarningsMismatch=(s:{id:string;vendorId:string;vendorNetEntitlement:Decimal;ledgerEntries:Array<{type:string;amount:Decimal}>}):Fact[]=>{const p=s.ledgerEntries.filter(x=>x.type==="SALE_PENDING");return !p.length?[make("PAYMENT_COMPLETED_LEDGER_MISSING","VENDOR_EARNINGS","HIGH","SubOrder",s.id,{subOrderId:s.id,vendorId:s.vendorId})]:p.some(x=>!x.amount.equals(s.vendorNetEntitlement))?[make("SALE_PENDING_AMOUNT_MISMATCH","VENDOR_EARNINGS","HIGH","SubOrder",s.id,{subOrderId:s.id,vendorId:s.vendorId})]:[]};

/** Checks the immutable Phase 3G pending → release → available transfer. */
export const detectEarningsRelease=(s:{id:string;vendorId:string;orderId:string;vendorNetEntitlement:Decimal|null;status:string;order:{paymentStatus:string};ledgerEntries:Ledger[]}):Fact[]=>{
 if(s.status!=="DELIVERED"||s.order.paymentStatus!=="COMPLETED"||!s.vendorNetEntitlement)return [];
 const p=s.ledgerEntries.filter(x=>x.type==="SALE_PENDING"),r=s.ledgerEntries.filter(x=>x.type==="SALE_RELEASE"),a=s.ledgerEntries.filter(x=>x.type==="SALE_AVAILABLE"),ids={subOrderId:s.id,vendorId:s.vendorId,orderId:s.orderId};
 if(!p.length)return [make("RELEASE_WITHOUT_PENDING","VENDOR_EARNINGS","HIGH","SubOrder",s.id,ids)]; if(!r.length)return [make("EARNINGS_RELEASE_MISSING","VENDOR_EARNINGS","HIGH","SubOrder",s.id,ids)]; if(!a.length)return [make("EARNINGS_AVAILABLE_MISSING","VENDOR_EARNINGS","HIGH","SubOrder",s.id,ids)];
 if(p.length!==1||r.length!==1||a.length!==1||!p[0].amount.equals(s.vendorNetEntitlement)||!r[0].amount.equals(s.vendorNetEntitlement.negated())||!a[0].amount.equals(s.vendorNetEntitlement))return [make("EARNINGS_RELEASE_AMOUNT_MISMATCH","VENDOR_EARNINGS","HIGH","SubOrder",s.id,ids)];
 if(new Set([...p,...r,...a].map(x=>x.currency)).size!==1)return [make("EARNINGS_RELEASE_CURRENCY_MISMATCH","VENDOR_EARNINGS","HIGH","SubOrder",s.id,ids)];
 return new Set([...p,...r,...a].map(x=>x.paymentAttemptId)).size!==1||!p[0].paymentAttemptId?[make("EARNINGS_RELEASE_PAYMENT_MISMATCH","VENDOR_EARNINGS","HIGH","SubOrder",s.id,ids)]:[];
};

export const detectPayout=(p:{id:string;vendorId:string;amount:Decimal;currency:string|null;status:string;allocations:Array<{status:string;allocatedAmount:Decimal;vendorId:string;currency:string;earningLedger:{vendorId:string;currency:string|null}}>;ledgerEntries:Ledger[]}):Fact[]=>{
 const ids={vendorPayoutId:p.id,vendorId:p.vendorId},active=p.allocations.filter(x=>x.status==="ACTIVE"), terminal=["CANCELLED","REJECTED"].includes(p.status);
 if(terminal){if(active.length)return [make("ACTIVE_ALLOCATION_ON_TERMINAL_PAYOUT","PAYOUT","HIGH","VendorPayout",p.id,ids)];const release=p.ledgerEntries.filter(x=>x.type==="PAYOUT_RELEASE"),available=p.ledgerEntries.filter(x=>x.type==="PAYOUT_AVAILABLE");return total(release).negated().equals(p.amount)&&total(available).equals(p.amount)?[]:[make("PAYOUT_RELEASE_MISMATCH","PAYOUT","HIGH","VendorPayout",p.id,ids)]}
 if(!["REQUESTED","APPROVED","READY_FOR_DISBURSEMENT"].includes(p.status))return []; if(!active.length)return [make("PAYOUT_ALLOCATION_MISSING","PAYOUT","HIGH","VendorPayout",p.id,ids)];
 if(!active.reduce((n,x)=>n.plus(x.allocatedAmount),ZERO).equals(p.amount)||active.some(x=>x.vendorId!==p.vendorId||x.currency!==p.currency||x.earningLedger.vendorId!==p.vendorId||x.earningLedger.currency!==p.currency))return [make("PAYOUT_ALLOCATION_MISMATCH","PAYOUT","HIGH","VendorPayout",p.id,ids)];
 const reserved=p.ledgerEntries.filter(x=>x.type==="PAYOUT_RESERVED"&&x.walletBucket==="RESERVED");if(!reserved.length)return [make("PAYOUT_RESERVATION_MISSING","PAYOUT","HIGH","VendorPayout",p.id,ids)];return total(reserved).equals(p.amount)&&!reserved.some(x=>x.vendorId!==p.vendorId||x.currency!==p.currency)?[]:[make("PAYOUT_RESERVATION_MISMATCH","PAYOUT","HIGH","VendorPayout",p.id,ids)];
};

export const detectRefund=(r:{id:string;orderId:string;subOrderId:string;amount:Decimal;platformCommissionAdjustment:Decimal;vendorLiabilityAdjustment:Decimal;shippingAmount:Decimal;gatewayFeeAdjustment:Decimal;status:string;items:Array<{orderItemId:string;quantity:number;grossAmount:Decimal;orderItem:{subOrderId:string;quantity:number;totalPrice:Decimal}|null}>}):Fact[]=>{const ids={refundId:r.id,orderId:r.orderId,subOrderId:r.subOrderId};if(!total(r.items.map(x=>({amount:x.grossAmount}))).equals(r.amount))return [make("REFUND_ITEM_GROSS_MISMATCH","REFUND","HIGH","Refund",r.id,ids)];if(!r.shippingAmount.equals(ZERO)||!r.gatewayFeeAdjustment.equals(ZERO)||!r.platformCommissionAdjustment.plus(r.vendorLiabilityAdjustment).equals(r.amount))return [make("REFUND_ECONOMICS_MISMATCH","REFUND","HIGH","Refund",r.id,ids)];if(r.items.some(x=>!x.orderItem||x.orderItem.subOrderId!==r.subOrderId||x.quantity<=0))return [make("REFUND_ITEM_REFERENCE_INVALID","REFUND","HIGH","Refund",r.id,ids)];return r.items.some(x=>!x.grossAmount.equals(x.orderItem!.totalPrice.div(x.orderItem!.quantity).times(x.quantity)))?[make("REFUND_ITEM_GROSS_MISMATCH","REFUND","HIGH","Refund",r.id,ids)]:[]};

export const detectReversal=(a:{id:string;orderId:string;status:string;ledgerEntries:Ledger[]}):Fact[]=>{if(a.status!=="REVERSED")return [];const original=a.ledgerEntries.filter(x=>x.type==="SALE_PENDING"||x.type==="SALE_AVAILABLE"),reversed=a.ledgerEntries.filter(x=>x.type==="SALE_REVERSAL_PENDING"||x.type==="SALE_REVERSAL_AVAILABLE"),ids={paymentAttemptId:a.id,orderId:a.orderId};if(!original.length||!reversed.length)return [make("REVERSAL_ADJUSTMENT_MISSING","REVERSAL","HIGH","PaymentAttempt",a.id,ids)];for(const x of original){const type=x.type==="SALE_PENDING"?"SALE_REVERSAL_PENDING":"SALE_REVERSAL_AVAILABLE",match=reversed.filter(y=>y.type===type&&y.subOrderId===x.subOrderId);if(match.length>1)return [make("REVERSAL_ADJUSTMENT_DUPLICATE","REVERSAL","HIGH","PaymentAttempt",a.id,ids)];if(!match.length)return [make("REVERSAL_ADJUSTMENT_MISSING","REVERSAL","HIGH","PaymentAttempt",a.id,ids)];if(!match[0].amount.equals(x.amount.negated())||match[0].currency!==x.currency)return [make("REVERSAL_AMOUNT_MISMATCH","REVERSAL","HIGH","PaymentAttempt",a.id,ids)];if(match[0].walletBucket!==(type==="SALE_REVERSAL_PENDING"?"PENDING":"AVAILABLE"))return [make("REVERSAL_BUCKET_MISMATCH","REVERSAL","HIGH","PaymentAttempt",a.id,ids)]}return []};

export class ReconciliationService {
 static async persist(f:Fact){return prisma.reconciliationFinding.upsert({where:{type_entityType_entityId:{type:f.type,entityType:f.entityType,entityId:f.entityId}},create:f,update:{status:ReconciliationFindingStatus.OPEN,detectedAt:new Date(),resolvedAt:null,resolution:null,metadata:f.metadata}})}
 private static async scan(domain:ReconciliationDomain,facts:Fact[]){const seen=new Set(facts.map(x=>`${x.type}:${x.entityType}:${x.entityId}`));for(const f of facts)await this.persist(f);const open=await prisma.reconciliationFinding.findMany({where:{domain,status:"OPEN"},select:{id:true,type:true,entityType:true,entityId:true}});const stale=open.filter(x=>!seen.has(`${x.type}:${x.entityType}:${x.entityId}`));if(stale.length)await prisma.reconciliationFinding.updateMany({where:{id:{in:stale.map(x=>x.id)}},data:{status:"RESOLVED",resolvedAt:new Date(),resolution:"AUTO_RECONCILED"}});return facts.length}
 static async run(scope:ReconciliationScope="ALL"){await requireAdminContext("platform:manage_billing");const result:Record<string,number>={};if(scope==="ALL"||scope==="PAYMENTS"){const rows=await prisma.paymentAttempt.findMany({where:{status:"COMPLETED"},include:{order:{select:{paymentStatus:true}}},take:BATCH_SIZE});result.PAYMENTS=await this.scan("PAYMENT",rows.flatMap(detectPaymentOrderMismatch))}if(scope==="ALL"||scope==="EARNINGS"){const rows=await prisma.subOrder.findMany({where:{status:"DELIVERED",order:{paymentStatus:"COMPLETED"}},include:{order:{select:{paymentStatus:true}},ledgerEntries:true},take:BATCH_SIZE});result.EARNINGS=await this.scan("VENDOR_EARNINGS",rows.flatMap(detectEarningsRelease))}if(scope==="ALL"||scope==="PAYOUTS"){const rows=await prisma.vendorPayout.findMany({include:{allocations:{include:{earningLedger:{select:{vendorId:true,currency:true}}}},ledgerEntries:true},take:BATCH_SIZE});result.PAYOUTS=await this.scan("PAYOUT",rows.flatMap(detectPayout))}if(scope==="ALL"||scope==="REFUNDS"){const rows=await prisma.refund.findMany({include:{items:{include:{orderItem:{select:{subOrderId:true,quantity:true,totalPrice:true}}}}},take:BATCH_SIZE});const facts=rows.flatMap(detectRefund), capacity=new Map<string,{quantity:number;gross:Decimal;max:number;value:Decimal}>();for(const r of rows)for(const i of r.items)if(i.orderItem){const c=capacity.get(i.orderItemId)??{quantity:0,gross:ZERO,max:i.orderItem.quantity,value:i.orderItem.totalPrice};c.quantity+=i.quantity;c.gross=c.gross.plus(i.grossAmount);capacity.set(i.orderItemId,c)}for(const [id,c]of capacity)if(c.quantity>c.max||c.gross.greaterThan(c.value))facts.push(make("REFUND_CAPACITY_EXCEEDED","REFUND","HIGH","OrderItem",id));result.REFUNDS=await this.scan("REFUND",facts)}if(scope==="ALL"||scope==="REVERSALS"){const rows=await prisma.paymentAttempt.findMany({where:{status:"REVERSED"},include:{ledgerEntries:true},take:BATCH_SIZE});result.REVERSALS=await this.scan("REVERSAL",rows.flatMap(detectReversal))}if(scope==="ALL"||scope==="RISK"){const rows=await prisma.vendorPayout.findMany({where:{status:"READY_FOR_DISBURSEMENT"},select:{id:true,vendorId:true},take:BATCH_SIZE}),facts:Fact[]=[];for(const row of rows){const check=await PayoutReadinessService.evaluateWithdrawalDisbursementEligibility(row.id);if(!check.eligible)facts.push(make("PAYOUT_READINESS_INCONSISTENT","RISK","CRITICAL","VendorPayout",row.id,{vendorPayoutId:row.id,vendorId:row.vendorId},{blockers:check.reasons}))}result.RISK=await this.scan("RISK",facts)}return {findings:Object.values(result).reduce((a,b)=>a+b,0),byScope:result}}
 static async listOpen(){await requireAdminContext("platform:manage_billing");return prisma.reconciliationFinding.findMany({where:{status:"OPEN"},orderBy:{detectedAt:"desc"}})}
 static async getFindingForCurrentAdmin(id:string){await requireAdminContext("platform:manage_billing");const f=await prisma.reconciliationFinding.findUnique({where:{id}});if(!f)throw Error("Finding not found.");return {...f,repairCapability:["PAYMENT_COMPLETED_LEDGER_MISSING","EARNINGS_RELEASE_MISSING","EARNINGS_AVAILABLE_MISSING","REVERSAL_ADJUSTMENT_MISSING"].includes(f.type)?"DETERMINISTIC":"MANUAL_REVIEW_REQUIRED"}}
 static async transition(id:string,status:"RESOLVED"|"IGNORED",reason:string){const admin=await requireAdminContext("platform:manage_billing");if(!reason.trim())throw Error("A resolution reason is required.");const finding=await prisma.reconciliationFinding.findUnique({where:{id}});if(!finding)throw Error("Finding not found.");const updated=await prisma.reconciliationFinding.update({where:{id},data:{status,resolvedAt:new Date(),resolution:reason.trim()}});await prisma.auditLog.create({data:{userId:admin.userId,action:`RECONCILIATION_FINDING_${status}`,entity:"ReconciliationFinding",entityId:id,newValues:{reason:reason.trim()}}});return updated}
 static async repair(id:string){const admin=await requireAdminContext("platform:manage_billing"),f=await prisma.reconciliationFinding.findUnique({where:{id}});if(!f)throw Error("Finding not found.");try{if(f.type==="PAYMENT_COMPLETED_LEDGER_MISSING"&&f.orderId&&f.paymentAttemptId)await MarketplaceEconomicsService.allocatePaidOrderEconomics(f.orderId,f.paymentAttemptId);else if((f.type==="EARNINGS_RELEASE_MISSING"||f.type==="EARNINGS_AVAILABLE_MISSING")&&f.subOrderId)await MarketplaceEconomicsService.releaseVendorEarningsForSubOrder(f.subOrderId);else if(f.type==="REVERSAL_ADJUSTMENT_MISSING"&&f.paymentAttemptId)await ReturnsRefundsService.reversePaymentEarnings(f.paymentAttemptId);else throw Error("MANUAL_REVIEW_REQUIRED");const updated=await prisma.reconciliationFinding.update({where:{id},data:{status:"RESOLVED",resolvedAt:new Date(),resolution:"AUTO_REPAIRED"}});await prisma.auditLog.create({data:{userId:admin.userId,action:"RECONCILIATION_REPAIR_SUCCEEDED",entity:"ReconciliationFinding",entityId:id,newValues:{type:f.type}}});return updated}catch(error){await prisma.auditLog.create({data:{userId:admin.userId,action:"RECONCILIATION_REPAIR_FAILED",entity:"ReconciliationFinding",entityId:id,newValues:{type:f.type}}});throw error}}
}
