"use client";

import * as React from "react";
import { type ColumnDef } from "@tanstack/react-table";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { DataTable } from "@/components/data-table";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { DeleteDialog } from "@/components/alert-dialog";
import { humanizeOperation, operationBadgeClass, shortReference } from "@/lib/admin-operations";

type Finding={id:string;type:string;domain:string;severity:string;status:string;entityType:string;entityId:string;detectedAt:string;metadata?:unknown};
type Flag={id:string;scope:string;category:string;severity:string;status:string;reason:string;createdAt:string;vendorId?:string;orderId?:string;subOrderId?:string;payoutId?:string};
type Tab="reconciliation"|"risk";
const date=(v?:string)=>v?new Intl.DateTimeFormat("en-UG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v)):"—";
const Badge=({value}:{value:string})=><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-semibold ${operationBadgeClass(value)}`}>{humanizeOperation(value)}</span>;

export default function FinancialExceptionsPage(){
 const [tab,setTab]=React.useState<Tab>("reconciliation"); const [findings,setFindings]=React.useState<Finding[]>([]); const [flags,setFlags]=React.useState<Flag[]>([]); const [loading,setLoading]=React.useState(true);const [error,setError]=React.useState("");const [selected,setSelected]=React.useState<Finding|Flag|null>(null);const [reason,setReason]=React.useState("");const [confirm,setConfirm]=React.useState<{action:string; item:Finding|Flag}|null>(null);const [saving,setSaving]=React.useState(false);
 const load=React.useCallback(async()=>{setLoading(true);setError("");try{const [a,b]=await Promise.all([fetch("/api/admin/reconciliation/findings",{cache:"no-store"}),fetch("/api/admin/risk-flags",{cache:"no-store"})]);const [aj,bj]=await Promise.all([a.json(),b.json()]);if(!a.ok||!aj.success)throw new Error(aj.error||"Unable to load reconciliation findings.");if(!b.ok||!bj.success)throw new Error(bj.error||"Unable to load risk flags.");setFindings(aj.data);setFlags(bj.data);}catch(e){setError(e instanceof Error?e.message:"Unable to load financial exceptions.");}finally{setLoading(false);}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- initial authenticated API request populates local view state
 React.useEffect(()=>{void load()},[load]);
 const mutate=async(action:string,item:Finding|Flag)=>{setSaving(true);try{const isFinding=tab==="reconciliation";let endpoint=isFinding?`/api/admin/reconciliation/findings/${item.id}`:`/api/admin/risk-flags/${item.id}`;let method="PATCH";let body:Record<string,string>={};if(action==="repair"){endpoint+= "/repair";method="POST";}else body=isFinding?{status:action,reason}:{status:action,resolution:reason};if(action!=="repair"&&!reason.trim())throw new Error("A resolution reason is required.");const r=await fetch(endpoint,{method,headers:{"content-type":"application/json"},body:method==="POST"?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||"Action could not be completed.");toast.success(action==="repair"?"Finding repaired using existing server logic.":"Exception updated.");setConfirm(null);setSelected(null);setReason("");await load();}catch(e){toast.error(e instanceof Error?e.message:"Action could not be completed.");}finally{setSaving(false)}};
 const findingColumns=React.useMemo<ColumnDef<Finding>[]>(()=>[{accessorKey:"type",header:"Finding",cell:({row})=><button className="max-w-[260px] truncate text-left font-medium hover:text-primary" onClick={()=>setSelected(row.original)}>{humanizeOperation(row.original.type)}</button>},{accessorKey:"domain",header:"Domain",cell:({row})=>humanizeOperation(row.original.domain)},{accessorKey:"severity",header:"Severity",cell:({row})=><Badge value={row.original.severity}/>},{accessorKey:"entityId",header:"Reference",cell:({row})=><span className="font-mono text-xs text-muted-foreground" title={row.original.entityId}>{shortReference(row.original.entityId)}</span>},{accessorKey:"detectedAt",header:"Detected",cell:({row})=>date(row.original.detectedAt)},{id:"action",header:"",cell:({row})=><Button size="sm" variant="outline" className="h-8 rounded-lg text-xs" onClick={()=>setSelected(row.original)}>Review</Button>}],[]);
 const flagColumns=React.useMemo<ColumnDef<Flag>[]>(()=>[{accessorKey:"category",header:"Category",cell:({row})=><button className="max-w-[260px] truncate text-left font-medium hover:text-primary" onClick={()=>setSelected(row.original)}>{humanizeOperation(row.original.category)}</button>},{accessorKey:"scope",header:"Scope",cell:({row})=>humanizeOperation(row.original.scope)},{accessorKey:"severity",header:"Severity",cell:({row})=><Badge value={row.original.severity}/>},{accessorKey:"reason",header:"Reason",cell:({row})=><span className="block max-w-[240px] truncate" title={row.original.reason}>{row.original.reason}</span>},{accessorKey:"createdAt",header:"Raised",cell:({row})=>date(row.original.createdAt)},{id:"action",header:"",cell:({row})=><Button size="sm" variant="outline" className="h-8 rounded-lg text-xs" onClick={()=>setSelected(row.original)}>Review</Button>}],[]);
 const isFinding=tab==="reconciliation"; const current=selected as Finding|undefined;const repairable=!!current&&"type"in current&&["PAYMENT_COMPLETED_LEDGER_MISSING","EARNINGS_RELEASE_MISSING","EARNINGS_AVAILABLE_MISSING","REVERSAL_ADJUSTMENT_MISSING"].includes(current.type);
 return <><div className="space-y-6 p-4 md:p-6"><div><h1 className="text-2xl font-semibold tracking-tight">Financial exceptions</h1><p className="mt-1 text-sm text-muted-foreground">Review reconciliation findings and Admin-only risk flags. This workspace does not approve withdrawals or investigate payments.</p></div>{error?<div className="rounded-xl border border-rose-500/30 bg-rose-500/5 p-4 text-sm text-rose-700"><p>{error}</p><Button variant="outline" size="sm" className="mt-3" onClick={()=>void load()}>Try again</Button></div>:<DataTable columns={(isFinding?findingColumns:flagColumns) as ColumnDef<Finding | Flag>[]} data={(isFinding?findings:flags) as Array<Finding | Flag>} getRowId={(r)=>r.id} isLoading={loading} renderTabs={<div className="flex flex-wrap gap-2" role="tablist" aria-label="Financial exception types"><Button variant={isFinding?"default":"outline"} size="sm" className="rounded-lg" role="tab" aria-selected={isFinding} onClick={()=>setTab("reconciliation")}>Reconciliation <span className="ml-1 opacity-70">{findings.length}</span></Button><Button variant={!isFinding?"default":"outline"} size="sm" className="rounded-lg" role="tab" aria-selected={!isFinding} onClick={()=>setTab("risk")}>Risk flags <span className="ml-1 opacity-70">{flags.length}</span></Button></div>}/>}</div>
 <Sheet open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{isFinding?"Reconciliation finding":"Risk flag"}</SheetTitle><SheetDescription>Reference <span className="font-mono">{selected?.id}</span></SheetDescription></SheetHeader>{selected&&<div className="mt-6 space-y-5 text-sm">{isFinding?<><div className="grid grid-cols-2 gap-3"><div><p className="text-muted-foreground">Domain</p><p>{humanizeOperation((selected as Finding).domain)}</p></div><div><p className="text-muted-foreground">Severity</p><Badge value={(selected as Finding).severity}/></div><div><p className="text-muted-foreground">Entity</p><p>{humanizeOperation((selected as Finding).entityType)}</p></div><div><p className="text-muted-foreground">Reference</p><p className="font-mono text-xs" title={(selected as Finding).entityId}>{shortReference((selected as Finding).entityId)}</p></div></div><p className="font-medium">{humanizeOperation((selected as Finding).type)}</p>{(selected as Finding).metadata&&<details className="rounded-lg border p-3 text-xs text-muted-foreground"><summary className="cursor-pointer">Technical metadata</summary><pre className="mt-2 whitespace-pre-wrap break-words">{JSON.stringify((selected as Finding).metadata,null,2)}</pre></details>}</>:<><div className="grid grid-cols-2 gap-3"><div><p className="text-muted-foreground">Scope</p><p>{humanizeOperation((selected as Flag).scope)}</p></div><div><p className="text-muted-foreground">Severity</p><Badge value={(selected as Flag).severity}/></div></div><p className="font-medium">{humanizeOperation((selected as Flag).category)}</p><p className="whitespace-pre-wrap break-words">{(selected as Flag).reason}</p></>}<Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Resolution note (required for resolve, ignore, or dismiss)"/>{isFinding?<div className="grid gap-2"><Button onClick={()=>setConfirm({item:selected,action:"RESOLVED"})}>Resolve</Button><Button variant="outline" onClick={()=>setConfirm({item:selected,action:"IGNORED"})}>Ignore with note</Button>{repairable&&<Button variant="outline" onClick={()=>setConfirm({item:selected,action:"repair"})}>Run deterministic repair</Button>}</div>:<div className="grid gap-2"><Button onClick={()=>setConfirm({item:selected,action:"RESOLVED"})}>Resolve</Button><Button variant="outline" onClick={()=>setConfirm({item:selected,action:"DISMISSED"})}>Dismiss</Button></div>}</div>}</SheetContent></Sheet>
 <DeleteDialog open={!!confirm} onOpenChange={o=>!o&&setConfirm(null)} title="Confirm financial operation" description={confirm?.action==="repair"?"Run the service’s deterministic repair for this finding? The server will audit the result.":"Record this authorized exception transition with the supplied note?"} itemType="action" variant="warning" isDeleting={saving} onConfirm={async()=>{if(confirm)await mutate(confirm.action,confirm.item)}}/>
 </>;
}
