import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({
  activeUser: vi.fn(), admin: vi.fn(), product: vi.fn(), shop: vi.fn(), existing: vi.fn(), reportCreate: vi.fn(), activity: vi.fn(), notification: vi.fn(), reportFind: vi.fn(), reportUpdate: vi.fn(), audit: vi.fn(), note: vi.fn(), user: vi.fn(), transaction: vi.fn(), reportList: vi.fn(), reportCustomer: vi.fn(),
}));
vi.mock("@/lib/auth/session", () => ({ requireActiveUserId: mocks.activeUser }));
vi.mock("@/lib/auth/admin-context", () => ({ requireAdminContext: mocks.admin }));
vi.mock("@/lib/prisma/client", () => ({ prisma: { product: { findFirst: mocks.product }, vendorProfile: { findFirst: mocks.shop }, marketplaceReport: { findFirst: mocks.existing, findUnique: mocks.reportFind, findMany: mocks.reportList, create: mocks.reportCreate, update: mocks.reportUpdate }, user: { findFirst: mocks.user }, $transaction: mocks.transaction } }));
import { MarketplaceReportError, MarketplaceReportService } from "@/services/marketplace-reports";

const product = { id: "product-1", name: "Safe kettle", slug: "safe-kettle", vendorId: "shop-1", vendor: { storeName: "Kampala Goods" }, images: [{ url: "image.jpg" }] };
const base = { id: "report-1", publicId: "RPT-2026-1", reporterId: "customer-1", status: "SUBMITTED", severity: "UNASSESSED", targetTitleSnapshot: "Safe kettle" };
describe("MarketplaceReportService", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.activeUser.mockResolvedValue("customer-1"); mocks.admin.mockResolvedValue({ userId: "admin-1", platformRole: "SUPPORT" }); mocks.product.mockResolvedValue(product); mocks.shop.mockResolvedValue(null); mocks.existing.mockResolvedValue(null); mocks.reportCreate.mockImplementation(({ data }: any) => ({ ...base, ...data })); mocks.reportFind.mockResolvedValue(base); mocks.reportUpdate.mockImplementation(({ data }: any) => ({ ...base, ...data })); mocks.transaction.mockImplementation((arg: any) => typeof arg === "function" ? arg({ marketplaceReport: { create: mocks.reportCreate, update: mocks.reportUpdate, findUnique: mocks.reportFind }, marketplaceReportActivity: { create: mocks.activity }, marketplaceReportNote: { create: mocks.note }, notification: { create: mocks.notification }, auditLog: { create: mocks.audit } }) : Promise.all(arg)); });
  it("derives the reporter from the session, stores snapshots, activity and a safe receipt link", async () => { const report = await MarketplaceReportService.createForCurrentUser({ targetType: "PRODUCT", targetId: "product-1", reason: "COUNTERFEIT", description: "Forged brand marks" }); expect(report).toMatchObject({ reporterId: "customer-1", status: "SUBMITTED", severity: "UNASSESSED", targetTitleSnapshot: "Safe kettle" }); expect(mocks.reportCreate).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ reporterId: "customer-1", productId: "product-1", vendorNameSnapshot: "Kampala Goods" }) })); expect(mocks.activity).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ type: "REPORT_CREATED" }) })); expect(mocks.notification).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ userId: "customer-1", actionPath: "/account/reports/report-1" }) })); });
  it("rejects invalid target/reason, missing Other detail, and duplicate active reports", async () => { await expect(MarketplaceReportService.createForCurrentUser({ targetType: "PRODUCT", targetId: "product-1", reason: "IMPERSONATION" as never })).rejects.toBeInstanceOf(MarketplaceReportError); await expect(MarketplaceReportService.createForCurrentUser({ targetType: "PRODUCT", targetId: "product-1", reason: "OTHER" })).rejects.toThrow("short explanation"); mocks.existing.mockResolvedValue({ publicId: "RPT-existing" }); await expect(MarketplaceReportService.createForCurrentUser({ targetType: "PRODUCT", targetId: "product-1", reason: "COUNTERFEIT" })).rejects.toMatchObject({ code: "DUPLICATE" }); });
  it("enforces lifecycle transitions before writes and does not notify for severity", async () => { await expect(MarketplaceReportService.transition("report-1", "RESOLVED", "NO_VIOLATION", "done")).rejects.toThrow("not allowed"); expect(mocks.reportUpdate).not.toHaveBeenCalled(); expect(mocks.notification).not.toHaveBeenCalled(); await MarketplaceReportService.setSeverity("report-1", "HIGH"); expect(mocks.activity).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ type: "SEVERITY_CHANGED" }) })); expect(mocks.audit).toHaveBeenCalled(); expect(mocks.notification).not.toHaveBeenCalled(); });
  it("requires closure metadata and writes customer-safe status notification", async () => { mocks.reportFind.mockResolvedValue({ ...base, status: "UNDER_REVIEW" }); await expect(MarketplaceReportService.transition("report-1", "RESOLVED")).rejects.toThrow("meaningful resolution"); await MarketplaceReportService.transition("report-1", "RESOLVED", "NO_VIOLATION", "No policy breach found."); expect(mocks.reportUpdate).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: "RESOLVED", resolvedById: "admin-1" }) })); expect(mocks.notification).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ userId: "customer-1", actionPath: "/account/reports/report-1" }) })); });
  it("creates immutable admin notes from the authorized actor without customer notification", async () => { mocks.note.mockResolvedValue({ id: "note-1" }); await MarketplaceReportService.addNote("report-1", "Checked listing history"); expect(mocks.note).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ adminId: "admin-1" }) })); expect(mocks.activity).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ type: "NOTE_ADDED" }) })); expect(mocks.notification).not.toHaveBeenCalled(); });
});
