/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-function-type */
import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({tx:vi.fn(),sub:vi.fn(),disputeCreate:vi.fn(),disputeFind:vi.fn(),disputeFirst:vi.fn(),disputeUpdate:vi.fn(),riskCreate:vi.fn(),riskFind:vi.fn(),riskUpdate:vi.fn(),audit:vi.fn(),user:vi.fn(),vendor:vi.fn(),admin:vi.fn(),refund:vi.fn()}));
vi.mock("@/lib/prisma/client",()=>({prisma:{$transaction:mocks.tx,dispute:{findMany:vi.fn(),findFirst:mocks.disputeFirst,findUnique:mocks.disputeFind,create:mocks.disputeCreate,update:mocks.disputeUpdate},riskFlag:{create:mocks.riskCreate,findMany:vi.fn(),findUnique:mocks.riskFind,update:mocks.riskUpdate},auditLog:{create:mocks.audit}}}));
vi.mock("@/lib/auth/session",()=>({getCurrentUserId:mocks.user}));vi.mock("@/lib/auth/vendor-context",()=>({requireVendorContext:mocks.vendor}));vi.mock("@/lib/auth/admin-context",()=>({requireAdminContext:mocks.admin}));vi.mock("@/services/returns-refunds",()=>({ReturnsRefundsService:{createRefundReservation:mocks.refund}}));
import { DisputeRiskService, DISPUTE_WINDOW_DAYS } from "@/services/disputes-risk";
const delivery=new Date("2026-01-01T00:00:00.000Z");const active={id:"d",status:"OPEN"};const sub=(x:any={})=>({id:"sub-a",orderId:"order-a",vendorId:"vendor-a",status:"DELIVERED",deliveryConfirmedAt:delivery,order:{customerId:"customer-a"},disputes:[],...x});const tx={subOrder:{findUnique:mocks.sub},dispute:{create:mocks.disputeCreate},auditLog:{create:mocks.audit}};
beforeEach(()=>{vi.clearAllMocks();mocks.tx.mockImplementation((f:Function)=>f(tx));mocks.user.mockResolvedValue("customer-a");mocks.vendor.mockResolvedValue({vendorId:"vendor-a"});mocks.admin.mockResolvedValue({userId:"admin-a"});mocks.sub.mockResolvedValue(sub());mocks.disputeCreate.mockImplementation(({data}:any)=>({id:"d",status:"OPEN",...data}));mocks.riskCreate.mockImplementation(({data}:any)=>({id:"risk",status:"OPEN",...data}));});
describe("Phase 3L disputes and operational risk",()=>{
 it("allows a customer to open only an own delivered dispute inside the centralized 30-day window and audits without ledger writes",async()=>{expect(DISPUTE_WINDOW_DAYS).toBe(30);await expect(DisputeRiskService.openForCurrentCustomer({subOrderId:"sub-a",reason:"missing",description:"details"},new Date("2026-01-31T00:00:00.000Z"))).resolves.toMatchObject({id:"d"});expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({action:"DISPUTE_OPENED"})}));expect(mocks.refund).not.toHaveBeenCalled();await expect(DisputeRiskService.openForCurrentCustomer({subOrderId:"sub-a",reason:"x",description:"x"},new Date("2026-01-31T00:00:00.001Z"))).rejects.toThrow("not eligible");});
 it("rejects cross-customer creation and makes duplicate active intent idempotent",async()=>{mocks.sub.mockResolvedValue(sub({order:{customerId:"customer-b"}}));await expect(DisputeRiskService.openForCurrentCustomer({subOrderId:"sub-a",reason:"x",description:"x"})).rejects.toThrow("not eligible");mocks.sub.mockResolvedValue(sub({disputes:[active]}));await expect(DisputeRiskService.openForCurrentCustomer({subOrderId:"sub-a",reason:"x",description:"x"},new Date("2026-01-02"))).resolves.toBe(active);expect(mocks.disputeCreate).not.toHaveBeenCalled();});
 it("requires platform support authority for review and reuses the Phase 3K Refund reservation for a customer resolution",async()=>{mocks.disputeFind.mockResolvedValue({id:"d",status:"UNDER_REVIEW",subOrderId:"sub-a",customerId:"customer-a",vendorId:"vendor-a",subOrder:{}});mocks.disputeUpdate.mockResolvedValue({id:"d",status:"RESOLVED_CUSTOMER"});await DisputeRiskService.transitionForCurrentAdmin("d","RESOLVED_CUSTOMER","refund",[{orderItemId:"item",quantity:1}]);expect(mocks.refund).toHaveBeenCalledWith(expect.objectContaining({subOrderId:"sub-a",requestedByUserId:"customer-a"}));expect(mocks.admin).toHaveBeenCalledWith("platform:customer_support");mocks.admin.mockRejectedValueOnce(new Error("Denied"));await expect(DisputeRiskService.transitionForCurrentAdmin("d","RESOLVED_VENDOR","ok")).rejects.toThrow("Denied");});
 it("allows only admins to create and resolve immutable-history risk flags; neither action moves money",async()=>{await DisputeRiskService.createRiskFlagForCurrentAdmin({scope:"VENDOR",category:"MANUAL_REVIEW",severity:"HIGH",vendorId:"vendor-a",reason:"manual hold"});expect(mocks.riskCreate).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({source:"ADMIN",createdByUserId:"admin-a"})}));mocks.riskFind.mockResolvedValue({id:"risk",status:"OPEN",vendorId:"vendor-a"});mocks.riskUpdate.mockResolvedValue({id:"risk",status:"RESOLVED"});await DisputeRiskService.resolveRiskFlagForCurrentAdmin("risk","RESOLVED","cleared");expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({action:"RISK_FLAG_RESOLVED"})}));expect(mocks.refund).not.toHaveBeenCalled();});
});
