import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ user: vi.fn(), transaction: vi.fn(), itemFind: vi.fn(), productFind: vi.fn(), productCreate: vi.fn(), subOrderFind: vi.fn(), shopCreate: vi.fn() }));
vi.mock("@/lib/auth/session", () => ({ requireActiveUserId: mocks.user }));
vi.mock("@/lib/prisma/client", () => ({ prisma: { $transaction: mocks.transaction, orderItem: { findFirst: mocks.itemFind }, productReview: { findUnique: mocks.productFind, create: mocks.productCreate }, subOrder: { findFirst: mocks.subOrderFind }, shopReview: { create: mocks.shopCreate } } }));
import { ReviewService } from "@/services/reviews";

const deliveredItem = { id: "item-a", productId: "product-a", variantId: "variant-a", order: { paymentStatus: "COMPLETED", status: "PAID" }, subOrder: { status: "DELIVERED", vendorId: "vendor-a" } };
describe("verified review eligibility", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.user.mockResolvedValue("customer-a"); mocks.itemFind.mockResolvedValue(deliveredItem); mocks.productFind.mockResolvedValue(null); mocks.productCreate.mockImplementation(async ({ data }: { data: object }) => ({ id: "review-a", ...data })); mocks.subOrderFind.mockResolvedValue({ id: "sub-a", vendorId: "vendor-a", status: "DELIVERED", order: { paymentStatus: "COMPLETED", status: "PAID" } }); mocks.shopCreate.mockImplementation(async ({ data }: { data: object }) => ({ id: "shop-review-a", ...data })); mocks.transaction.mockImplementation(async (callback: (tx: object) => unknown) => callback({ orderItem: { findFirst: mocks.itemFind }, productReview: { findUnique: mocks.productFind, create: mocks.productCreate }, shopReview: { create: mocks.shopCreate }, subOrder: { findFirst: mocks.subOrderFind } })); });
  it("creates a product review only for the session owner's paid, delivered item", async () => { await expect(ReviewService.createProductReviewForCurrentUser({ orderItemId: "item-a", rating: 5 })).resolves.toMatchObject({ orderItemId: "item-a", productId: "product-a", userId: "customer-a", verifiedPurchase: true }); expect(mocks.itemFind).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "item-a", order: { customerId: "customer-a" } } })); });
  it.each([{ paymentStatus: "PENDING", status: "PAID", subOrder: { status: "DELIVERED", vendorId: "vendor-a" } }, { paymentStatus: "COMPLETED", status: "PAID", subOrder: { status: "SHIPPED", vendorId: "vendor-a" } }, { paymentStatus: "COMPLETED", status: "REFUNDED", subOrder: { status: "DELIVERED", vendorId: "vendor-a" } }])("rejects non-qualifying payment, delivery, or refund states", async (order) => { mocks.itemFind.mockResolvedValue({ ...deliveredItem, order: { paymentStatus: order.paymentStatus, status: order.status }, subOrder: order.subOrder }); await expect(ReviewService.createProductReviewForCurrentUser({ orderItemId: "item-a", rating: 5 })).rejects.toMatchObject({ code: "INELIGIBLE" }); });
  it("prevents duplicate item submissions, including concurrent replays resolved by the database", async () => { mocks.productFind.mockResolvedValue({ id: "existing" }); await expect(ReviewService.createProductReviewForCurrentUser({ orderItemId: "item-a", rating: 4 })).rejects.toMatchObject({ code: "DUPLICATE" }); expect(mocks.productCreate).not.toHaveBeenCalled(); });
  it("keeps shop eligibility bound to the customer's own vendor sub-order", async () => { await expect(ReviewService.createShopReviewForCurrentUser({ subOrderId: "sub-a", rating: 4 })).resolves.toMatchObject({ vendorId: "vendor-a", userId: "customer-a" }); expect(mocks.subOrderFind).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "sub-a", order: { customerId: "customer-a" } } })); });
});
