"use client";
import { createContext, useContext, useEffect, useReducer, useRef, type ReactNode } from "react";
import { useAuth } from "@/providers/AuthProvider";
import { initialWorkspaceAccessState, noWorkspaces, type WorkspaceAccess, type WorkspaceAccessState, workspaceAccessReducer } from "@/lib/auth/workspace-access-state";
const WorkspaceAccessContext = createContext<Omit<WorkspaceAccessState, "identity" | "revision"> | undefined>(undefined);
export function WorkspaceAccessProvider({ children }: { children: ReactNode }) { const { isAuthenticated, uid, sessionReady, sessionRevision } = useAuth(); const [state, dispatch] = useReducer(workspaceAccessReducer, initialWorkspaceAccessState); const generation = useRef(0);
  useEffect(() => { const request = ++generation.current; if (!isAuthenticated || !uid) { dispatch({ type: "clear", identity: null, revision: sessionRevision, loading: false }); return; } if (!sessionReady) { dispatch({ type: "clear", identity: uid, revision: sessionRevision, loading: true }); return; } const controller = new AbortController(); dispatch({ type: "clear", identity: uid, revision: sessionRevision, loading: true }); void fetch("/api/auth", { signal: controller.signal, cache: "no-store" }).then(async (response) => { if (!response.ok) return noWorkspaces; const body = await response.json() as { data?: Partial<WorkspaceAccess> }; return { canAccessVendor: body.data?.canAccessVendor === true, canAccessAdmin: body.data?.canAccessAdmin === true }; }).then((access) => { if (!controller.signal.aborted && generation.current === request) dispatch({ type: "resolved", identity: uid, revision: sessionRevision, access }); }).catch(() => { if (!controller.signal.aborted && generation.current === request) dispatch({ type: "resolved", identity: uid, revision: sessionRevision, access: noWorkspaces }); }); return () => controller.abort(); }, [isAuthenticated, uid, sessionReady, sessionRevision]);
  return <WorkspaceAccessContext.Provider value={{ canAccessVendor: state.canAccessVendor, canAccessAdmin: state.canAccessAdmin, loading: state.loading }}>{children}</WorkspaceAccessContext.Provider>; }
export function useWorkspaceAccess() { const context = useContext(WorkspaceAccessContext); if (!context) throw new Error("useWorkspaceAccess must be used within WorkspaceAccessProvider"); return context; }
