"use client";
import { useState } from "react";
import { CreditCard, HelpCircle, Package, Search, Store } from "lucide-react";
import { mockDatabase } from "@/data/mockDatabase";
import { PageContainer } from "@/components/marketplace/page-container";
import { PageHeader } from "@/components/marketplace/page-header";
import { Input } from "@/components/ui/input";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
const categories=[{id:"all",label:"All topics",icon:HelpCircle},{id:"orders",label:"Orders & delivery",icon:Package},{id:"payments",label:"Payments",icon:CreditCard},{id:"vendors",label:"Shopping from shops",icon:Store}];
export default function HelpCenterPage(){const [search,setSearch]=useState("");const [category,setCategory]=useState("all");const faqs=mockDatabase.faqs.filter(f=> (category==="all"||f.category===category)&&(`${f.question} ${f.answer}`.toLowerCase().includes(search.toLowerCase())));return <PageContainer className="max-w-5xl py-6 pb-24 sm:py-8"><PageHeader title="Help & Support" description="Find answers or get help with your SmartDuka experience."/><div className="relative mt-7"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search help topics" className="h-12 rounded-full pl-11"/></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{categories.map(item=>{const Icon=item.icon;const selected=category===item.id;return <button key={item.id} onClick={()=>setCategory(item.id)} aria-pressed={selected} className={`min-h-20 rounded-xl border p-3 text-left ${selected?"border-primary bg-primary/5 text-primary":"bg-card hover:bg-muted"}`}><Icon className="size-4"/><span className="mt-3 block text-sm font-medium">{item.label}</span></button>})}</div><section className="mt-7 rounded-xl border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">Popular help topics</h2></div>{faqs.length?<Accordion type="single" collapsible className="px-5">{faqs.map(f=><AccordionItem key={f.id} value={f.id}><AccordionTrigger className="text-left text-sm font-medium hover:text-primary hover:no-underline">{f.question}</AccordionTrigger><AccordionContent className="text-sm leading-6 text-muted-foreground">{f.answer}</AccordionContent></AccordionItem>)}</Accordion>:<div className="px-5 py-12 text-center"><HelpCircle className="mx-auto size-6 text-muted-foreground"/><h2 className="mt-3 font-semibold">No help topics found</h2><p className="mt-1 text-sm text-muted-foreground">Try another search or browse a different topic.</p></div>}</section></PageContainer>}
