"use client";

import { ChevronsLeftIcon, ChevronLeftIcon, ChevronRightIcon, ChevronsRightIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function PaginationControls({ pageIndex, pageSize, pageCount, total, pageSizeOptions = [5, 10, 20, 30, 40, 50], onPageChange, onPageSizeChange }: { pageIndex: number; pageSize: number; pageCount: number; total?: number; pageSizeOptions?: number[]; onPageChange: (pageIndex: number) => void; onPageSizeChange: (pageSize: number) => void }) {
  const safePageCount = Math.max(1, pageCount);
  const safePageIndex = Math.min(Math.max(0, pageIndex), safePageCount - 1);
  const hasPrevious = safePageIndex > 0;
  const hasNext = safePageIndex < safePageCount - 1;
  return <div className="flex flex-col items-center justify-between gap-4 px-1 pt-2 sm:flex-row"><div className="flex-1 text-xs font-semibold text-muted-foreground">{total === undefined ? null : `${total} matching order${total === 1 ? "" : "s"}`}</div><div className="flex w-full items-center justify-between gap-4 sm:w-auto sm:justify-end lg:gap-8"><div className="hidden items-center gap-2.5 lg:flex"><Label htmlFor="rows-per-page" className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Rows per page</Label><Select value={`${pageSize}`} onValueChange={(value) => onPageSizeChange(Number(value))}><SelectTrigger size="sm" className="h-8 w-20 rounded-lg border-border/60 text-xs font-medium" id="rows-per-page"><SelectValue placeholder={pageSize} /></SelectTrigger><SelectContent side="top" className="rounded-xl border-border/60 p-1"><SelectGroup>{pageSizeOptions.map((size) => <SelectItem key={size} value={`${size}`} className="rounded-lg text-xs font-semibold">{size}</SelectItem>)}</SelectGroup></SelectContent></Select></div><div className="text-xs font-medium tracking-tight text-foreground">Page {safePageIndex + 1} of {safePageCount}</div><div className="flex items-center gap-1.5"><Button variant="outline" className="hidden h-8 w-8 rounded-lg border-border/60 p-0 transition-transform active:scale-95 lg:flex" onClick={() => onPageChange(0)} disabled={!hasPrevious} aria-label="First page"><ChevronsLeftIcon className="size-4 opacity-70" /></Button><Button variant="outline" className="size-8 rounded-lg border-border/60 transition-transform active:scale-95" size="icon" onClick={() => onPageChange(safePageIndex - 1)} disabled={!hasPrevious} aria-label="Previous page"><ChevronLeftIcon className="size-4 opacity-70" /></Button><Button variant="outline" className="size-8 rounded-lg border-border/60 transition-transform active:scale-95" size="icon" onClick={() => onPageChange(safePageIndex + 1)} disabled={!hasNext} aria-label="Next page"><ChevronRightIcon className="size-4 opacity-70" /></Button><Button variant="outline" className="hidden size-8 rounded-lg border-border/60 transition-transform active:scale-95 lg:flex" size="icon" onClick={() => onPageChange(safePageCount - 1)} disabled={!hasNext} aria-label="Last page"><ChevronsRightIcon className="size-4 opacity-70" /></Button></div></div></div>;
}
